source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'ZMJAreaPickerView_Example' do
  pod 'ZMJAreaPickerView', :path => '../'

  pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '~> 3.0.17'
  
  target 'ZMJAreaPickerView_Tests' do
    inherit! :search_paths

    
  end
end
